name: tag

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: tag test
        run: echo ${GITHUB_REF##*/}

      - name: tag script
        id: tag
        uses: actions/github-script@1.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context.payload.ref.replace(/\/refs\/tags\//, '');

      - name: echo tag
        run: echo ${{ steps.tag.outputs.result }}
